# Format: 以下のKey/Valueを含むNodeの配列
#
#   group: グループ名（厳密には任意だけどできるだけ書いて欲しい）
#   description: urlリストのソース情報（任意）
#   enabled: 出力に含めるかどうか（必須）
#   urls: 出力に含める URL の配列（必須）
#
---
- group: Atlassian
  enabled: true
  urls:
    - bitbucket.org
    - bitbucket-connect-icons.s3.amazonaws.com
    - "*.atlassian.com"
    - "*.atlassian.io"
    - "*.atlassian.net"
    - "*.atl-paas.net"
    - "*.bitbucket.org"
    - "*.cloudfront.net"
    - "*.gravatar.com"
    - "*.jira.com"
    - "*.newrelic.com"
    - "*.nr-data.net"
    - "*.statuspage.io"

- group: Amazon
  enabled: true
  urls:
    - aws.amazon.com
    - "*.amazon.com"
    - "*.amazon.co.jp"
    - "*.amazonaws.com"
    - "*.aws.amazon.com"
    - "*.cloudfront.net"

- group: Backlog
  description: https://support-ja.backlog.com/hc/ja/articles/360035645554-%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%E3%81%A7%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%82%92%E3%81%99%E3%81%B9%E3%81%A6%E6%95%99%E3%81%88%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84
  enabled: true
  urls:
    - backlog.com
    - backlog.jp
    - cacoo.com
    - typetalk.com
    - typekit.net
    - "*.backlog.com"
    - "*.backlog.jp"
    - "*.nulab.jp"
    - "*.stripe.com"
    - "*.intercom.io"
    - "*.intercomcdn.com"
    - "*.visualwebsiteoptimizer.com"

- group: GitHub
  enabled: true
  urls:
    - github.com
    - "*.github.com"
    - "*.githubapp.com"
    - "*.githubassets.com"
    - "*.githubusercontent.com"

- group: GitLab
  enabled: true
  urls:
    - gitlab.com
    - "*.gitlab.com"
    - "*.gitlab.net"
    - "*.gitlab-static.net"

- group: Google
  enabled: true
  urls:
    - gmail.com
    - "*.gmail.com"
    - "*.google.com"
    - "*.google.co.jp"
    - "*.google-analytics.com"
    - "*.googleadmanager.com"
    - "*.googleadservices.com"
    - "*.googleapis.com"
    - "*.googleusercontent.com"
    - "*.gstatic.com"
    - "*.youtube.com"

- group: Jobcan
  enabled: true
  urls:
    - cdnjs.cloudflare.com
    - fonts.googleapis.com
    - fonts.gstatic.com
    - "*.jobcan.jp"
    - "*.marketo.net"

- group: Localhost
  enabled: true
  urls:
    - localhost

- group: Microsoft
  description: |
    https://docs.microsoft.com/ja-jp/azure/security/fundamentals/azure-domains
    https://docs.microsoft.com/ja-jp/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
  enabled: true
  urls:
      # https://docs.microsoft.com/ja-jp/azure/security/fundamentals/azure-domains
    - "*.azure-api.net"
    - "*.azure-mobile.net"
    - "*.azure.com"
    - "*.azurecontainer.io"
    - "*.azurecr.io"
    - "*.azureedge.net"
    - "*.azurefd.net"
    - "*.azurewebsites.net"
    - "*.cloudapp.net"
    - "*.msecnd.net"
    - "*.onmicrosoft.com"
    - "*.trafficmanager.net"
    - "*.visualstudio.com"
    - "*.windows.net"
      # https://docs.microsoft.com/ja-jp/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
    - a.wunderlist.com
    - accounts.google.com
    - api.dropboxapi.com
    - api.login.yahoo.com
    - api.meetup.com
    - app.adjust.com
    - app.box.com
    - apps.identrust.com
    - bit.ly
    - cacerts.digicert.com
    - cert.int-x3.letsencrypt.org
    - connect.facebook.net
    - crl.globalsign.com
    - crl.globalsign.net
    - crl.identrust.com
    - crl.microsoft.com
    - crl3.digicert.com
    - crl4.digicert.com
    - data.flurry.com
    - graph.facebook.com
    - isrg.trustid.ocsp.identrust.com
    - m.facebook.com
    - mail.google.com
    - ocsp.digicert.com
    - ocsp.globalsign.com
    - ocsp.int-x3.letsencrypt.org
    - ocsp.msocsp.com
    - ocsp2.globalsign.com
    - ocspx.digicert.com
    - platform.linkedin.com
    - play.google.com
    - secure.globalsign.com
    - secure.meetup.com
    - social.yahooapis.com
    - staffhub.ms
    - sway.com
    - www.acompli.com
    - www.digicert.com
    - www.dropbox.com
    - www.evernote.com
    - www.google-analytics.com
    - www.googleapis.com
    - www.wunderlist.com
    - www.sway.com
    - www.youtube.com
    - "*.acompli.net"
    - "*.ad.atdmt.com"
    - "*.aka.ms"
    - "*.akadns.net"
    - "*.akamaihd.net"
    - "*.aspnetcdn.com"
    - "*.assets-yammer.com"
    - "*.atdmt.com"
    - "*.apple.com"
    - "*.assets-yammer.com"
    - "*.azure-apim.net"
    - "*.azure.com"
    - "*.azure.net"
    - "*.azureedge.net"
    - "*.bing.com"
    - "*.bing.net"
    - "*.cloudapp.net"
    - "*.cloudappsecurity.com"
    - "*.edgesuite.net"
    - "*.entrust.net"
    - "*.geotrust.com"
    - "*.getmicrosoftkey.com"
    - "*.gfx.ms"
    - "*.helpshift.com"
    - "*.hockeyapp.net"
    - "*.localytics.com"
    - "*.lync.com"
    - "*.live.com"
    - "*.live.net"
    - "*.microsoft.com"
    - "*.microsoftazuread-sso.com"
    - "*.microsoftonline-p.com"
    - "*.microsoftonline-p.net"
    - "*.microsoftonline.com"
    - "*.microsoftstream.com"
    - "*.microsoftusercontent.com"
    - "*.msauth.net"
    - "*.msauthimages.net"
    - "*.msecnd.net"
    - "*.msedge.net"
    - "*.msft.net"
    - "*.msftauth.net"
    - "*.msftauthimages.net"
    - "*.msftidentity.com"
    - "*.msidentity.com"
    - "*.msn.com"
    - "*.msocdn.com"
    - "*.mstea.ms"
    - "*.o365weve.com"
    - "*.oaspapps.com"
    - "*.office.com"
    - "*.office.net"
    - "*.office365.com"
    - "*.omniroot.com"
    - "*.onedrive.com"
    - "*.onestore.ms"
    - "*.onenote.net"
    - "*.onmicrosoft.com"
    - "*.optimizely.com"
    - "*.outlook.com"
    - "*.outlookmobile.com"
    - "*.phonefactor.net"
    - "*.powerapps.com"
    - "*.public-trust.com"
    - "*.sfbassets.com"
    - "*.sfx.ms"
    - "*.sharepoint.com"
    - "*.sharepointonline.com"
    - "*.signalr.net"
    - "*.skype.com"
    - "*.skypeassets.com"
    - "*.skypeforbusiness.com"
    - "*.svc.ms"
    - "*.sway-cdn.com"
    - "*.sway-extensions.com"
    - "*.symcb.com"
    - "*.symcd.com"
    - "*.tenor.com"
    - "*.trafficmanager.net"
    - "*.uservoice.com"
    - "*.verisign.com"
    - "*.verisign.net"
    - "*.visualstudio.com"
    - "*.virtualearth.net"
    - "*.windows-ppe.net"
    - "*.windows.com"
    - "*.windows.net"
    - "*.windowsazure.com"
    - "*.yammer.com"
    - "*.yammerusercontent.com"
    - "*.ytimg.com"

- group: Miro
  enabled: true
  urls:
    - miro.com
    - mirostatic.com
    - "*.miro.com"

- group: Slack
  description: https://timedia.slack.com/help/urls
  enabled: true
  urls:
    - slack.com
    - slackb.com
    - slack-files.com
    - slack-imgs.com
    - slack-redir.com
    - slack-redir.net
    - slack.global.ssl.fastly.net
    - "*.chime.aws"
    - "*.lb.slack-msgs.com"
    - "*.slack.com"
    - "*.slack-core.com"
    - "*.slack-edge.com"
    - "*.slack-imgs.com"

- group: SNS
  enabled: true
  urls:
    - facebook.com
    - fonts.gstatic.com
    - twitter.com
    - www.google-analytics.com
    - "*.facebook.com"
    - "*.fbcdn.net"
    - "*.gravatar.com"
    - "*.twimg.com"
    - "*.twitter.com"
    - "*.vein.space"

- group: xip.io
  enabled: true
  urls:
    - "*.xip.io"

- group: Zoom.us
  description: https://support.zoom.us/hc/ja/articles/201362683-Zoom%E3%81%AE%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%82%A1%E3%82%A4%E3%82%A2%E3%82%A6%E3%82%A9%E3%83%BC%E3%83%AB%E3%81%BE%E3%81%9F%E3%81%AF%E3%83%97%E3%83%AD%E3%82%AD%E3%82%B7%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%AE%E8%A8%AD%E5%AE%9A
  enabled: true
  urls:
    - zoom.us
    - "*.zoom.us"
